services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy
